openapi: 3.0.3
info:
  title: GymApp API
  description: API para gestión de usuarios, programas y ejercicios en una aplicación de gimnasio.
  version: 1.0.0

servers:
  - url: http://localhost:8080/api
    description: Entorno local de desarrollo

tags:
  - name: Ejercicios
  - name: Usuarios
  - name: Programas

paths:
  /ejercicios:
    get:
      tags: [Ejercicios]
      summary: Obtener todos los ejercicios
      responses:
        '200':
          description: Lista de ejercicios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ejercicio'
    post:
      tags: [Ejercicios]
      summary: Crear un nuevo ejercicio
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ejercicio'
      responses:
        '201':
          description: Ejercicio creado

  /ejercicios/{ejercicioId}:
    get:
      tags: [Ejercicios]
      summary: Obtener un ejercicio por ID
      parameters:
        - name: ejercicioId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Ejercicio encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ejercicio'
    put:
      tags: [Ejercicios]
      summary: Actualizar un ejercicio existente
      parameters:
        - name: ejercicioId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ejercicio'
      responses:
        '200':
          description: Ejercicio actualizado
    delete:
      tags: [Ejercicios]
      summary: Borrar un ejercicio
      parameters:
        - name: ejercicioId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Ejercicio borrado
        '404':
          description: Ejercicio no encontrado

  /usuarios:
    post:
      tags: [Usuarios]
      summary: Crear un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '201':
          description: Usuario creado

  /usuarios/{usuarioId}:
    get:
      tags: [Usuarios]
      summary: Obtener un usuario por ID
      parameters:
        - name: usuarioId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
    put:
      tags: [Usuarios]
      summary: Actualizar un usuario existente
      parameters:
        - name: usuarioId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '200':
          description: Usuario actualizado
    delete:
      tags: [Usuarios]
      summary: Borrar un usuario
      parameters:
        - name: usuarioId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Usuario borrado
        '404':
          description: Usuario no encontrado

  /programas/{programaId}:
    get:
      tags: [Programas]
      summary: Obtener un programa por ID
      parameters:
        - name: programaId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Programa encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Programa'
    delete:
      tags: [Programas]
      summary: Borrar un programa
      parameters:
        - name: programaId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Programa borrado
        '404':
          description: Programa no encontrado

  /usuarios/{usuarioId}/programa:
    get:
      tags: [Programas]
      summary: Obtener todos los programas de un usuario
      parameters:
        - name: usuarioId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Lista de programas del usuario
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Programa'

  /programas:
    post:
      tags: [Programas]
      summary: Crear un nuevo programa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Programa'
      responses:
        '201':
          description: Programa creado

components:
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        apellidos:
          type: string
        altura:
          type: integer
        peso:
          type: integer
        fechaNacimiento:
          type: string
          format: date
        programas:
          type: array
          items:
            $ref: '#/components/schemas/Programa'

    Ejercicio:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        grupoMuscular:
          type: string
        imagen:
          type: string
        descripcion:
          type: string

    Programa:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fechaInicio:
          type: string
          format: date
        fechaFin:
          type: string
          format: date
        usuario:
          $ref: '#/components/schemas/Usuario'
        ejercicios:
          type: array
          items:
            $ref: '#/components/schemas/ProgramaEjercicio'

    ProgramaEjercicio:
      type: object
      properties:
        id:
          type: integer
          format: int64
        ejercicio:
          $ref: '#/components/schemas/Ejercicio'
        repeticiones:
          type: integer
        series:
          type: integer
        descansos:
          type: integer
        dia:
          type: string
        notas:
          type: string
        programaId:
          type: integer
          format: int64
          description: ID del programa al que pertenece este ejercicio
